src/app/layout.tsx, src/app/noSSR.spec.tsx, src/components/atoms/DarkModeSwitch/DarkModeSwitch.spec.tsx, src/components/molecules/RegionSearch/RegionSearch.spec.tsx, src/components/molecules/TimeframeSearch.tsx/TimeframeSearch.spec.tsx, src/components/organisms/Header/Header.tsx, src/components/organisms/Header/__snapshots__/Header.spec.tsx.snap, src/locales/en/home.json, src/overmind/analytics/actions.ts, src/overmind/analytics/index.ts, src/overmind/index.ts
=> [POU-75] Clean project structure

.github/workflows/dev.yml, .github/workflows/sonar-analysis-on-pr.yml, .github/workflows/templates/checks/action.yml, .github/workflows/templates/deploy/action.yml
=> [POU-76] Setup deployment into static bucket

src/app/__snapshots__/page.spec.tsx.snap, src/components/molecules/RegionSearch/RegionSearch.tsx, src/components/molecules/RegionSearch/__snapshots__/RegionSearch.spec.tsx.snap, src/components/molecules/TimeframeSearch/TimeframeSearch.spec.tsx, src/components/molecules/TimeframeSearch/TimeframeSearch.tsx, src/components/molecules/TimeframeSearch/__snapshots__/TimeframeSearch.spec.tsx.snap, src/styles/Text.ts, src/styles/Theme.ts
[POU 50](https://cadtrust.atlassian.net/browse/POU-50)
To follow the timeframe selection and region search from the figma
Removed the cross and the filtering of the max value
Max is now displayed as default
Display ellipsis on the region
=> [POU-50] Removing cross from timeframe

.github/workflows/dev.yml, .github/workflows/templates/checks/action.yml, .github/workflows/templates/deploy/action.yml, .github/workflows/templates/env/action.yml, .github/workflows/templates/sonar-analysis/action.yml
=> [POU-76] Add env file and pipeline modifications

.github/workflows/dev.yml
=> [POU-76] Change on deploy step

src/overmind/searchFilters/effects.ts
[POU 101](https://cadtrust.atlassian.net/browse/POU-101)
To be able to pull data from backend
- Updating the endpoint to use V1
=> [POU-101] Updating governance endpoint 

src/app/__snapshots__/page.spec.tsx.snap, src/components/molecules/AutoComplete/AutoComplete.spec.tsx, src/components/molecules/AutoComplete/AutoComplete.tsx, src/components/molecules/AutoComplete/__snapshots__/AutoComplete.spec.tsx.snap, src/components/molecules/RegionSearch/__snapshots__/RegionSearch.spec.tsx.snap, src/components/organisms/CreditsHistorySection/__snapshots__/CreditsHistorySection.spec.tsx.snap, src/components/organisms/CreditsHistorySection/__snapshots__/IssuedRetiredChartHeader.spec.tsx.snap, src/components/organisms/Menu/Menu.tsx, src/components/organisms/Menu/__snapshots__/Menu.spec.tsx.snap, src/components/organisms/SearchBar/__snapshots__/SearchBar.spec.tsx.snap, src/locales/en/home.json, src/locales/en/menu.json, src/styles/Button.ts, src/styles/Input.ts
Some change requested from desk check with designer
=> [CHORE] Homepage design changes to search bar

.github/workflows/dev.yml, .github/workflows/pre-prod.yml, .github/workflows/templates/deploy/action.yml
=> [POU-105] Setup preprod pipelines for frontend

src/app/__snapshots__/page.spec.tsx.snap, src/app/page.tsx
Hot fix for page layout
The map section is not behaving as expected. Too much padding on the bottom.
Removed unnecessary flex and made the min-height min-content
=> [Hot fix] Page layout

src/app/__snapshots__/page.spec.tsx.snap, src/components/atoms/SelectableChip/SelectableChip.spec.tsx, src/components/atoms/SelectableChip/SelectableChip.tsx, src/components/atoms/SelectableChip/__snapshots__/SelectableChip.spec.tsx.snap, src/components/atoms/SubregionIndicator/SubregionIndicator.tsx, src/components/molecules/RegionSearch/RegionSearch.tsx, src/components/molecules/RegionSearch/__snapshots__/RegionSearch.spec.tsx.snap, src/components/molecules/TimeframeSearch/TimeframeSearch.spec.tsx, src/components/molecules/TimeframeSearch/TimeframeSearch.tsx, src/components/molecules/TimeframeSearch/__snapshots__/TimeframeSearch.spec.tsx.snap, src/components/organisms/CreditsHistorySection/IssuedRetiredChartHeader.tsx, src/components/organisms/CreditsHistorySection/__snapshots__/CreditsHistorySection.spec.tsx.snap, src/components/organisms/CreditsHistorySection/__snapshots__/IssuedRetiredChartHeader.spec.tsx.snap, src/components/organisms/SearchBar/__snapshots__/SearchBar.spec.tsx.snap, src/styles/Tag.ts, src/styles/Theme.ts
Some change requested from desk check
- back button on the region filter
- time frame filter
=> [Chore] Desk check changes

sonar-project.properties, src/@types/ProjectDetails.ts, src/app/project/[id]/__snapshots__/page.spec.tsx.snap, src/app/project/[id]/page.spec.tsx, src/app/project/[id]/page.tsx, src/app/search/projects/page.spec.tsx, src/components/atoms/ProjectDetailHeader/ProjectDetailHeader.tsx, src/components/atoms/ProjectDetailHeader/__snapshots__/ProjectDetailHeader.spec.tsx.snap, src/components/molecules/CardSection/CardSection.spec.tsx, src/components/molecules/CardSection/CardSection.tsx, src/components/molecules/CardSection/__snapshots__/CardSection.spec.tsx.snap, src/components/molecules/ProjectDetailsInfo/ProjectDetailsInfo.spec.tsx, src/components/molecules/ProjectDetailsInfo/ProjectDetailsInfo.tsx, src/components/molecules/ProjectDetailsInfo/__snapshots__/ProjectDetailsInfo.spec.tsx.snap, src/components/molecules/ProjectDetailsInfoSkeleton/ProjectDetailsInfoSkeleton.spec.tsx, src/components/molecules/ProjectDetailsInfoSkeleton/ProjectDetailsInfoSkeleton.tsx, src/components/molecules/ProjectDetailsInfoSkeleton/__snapshots__/ProjectDetailsInfoSkeleton.spec.tsx.snap, src/overmind/projectResult/effects.ts, src/styles/Section.ts, src/styles/Theme.ts, src/utils/UnitConverter.spec.ts, src/utils/UnitConverter.ts
[POU 118](https://cadtrust.atlassian.net/browse/POU-118)
Base widgets for the project details page
- page with dynamic id
- I18n
- Handling coordinate conversion
- Handling based page design
- Responsive wrap
=> [POU-118]: Base project details design

.github/workflows/dev.yml, .github/workflows/pre-prod.yml, .github/workflows/templates/env/action.yml, src/components/molecules/ProjectDetailsInfo/ProjectDetailsInfo.tsx, src/components/molecules/ProjectDetailsInfo/__snapshots__/ProjectDetailsInfo.spec.tsx.snap
Google map needs an API key to function
- Add github secret to workflow
=> [CI] Adding google map secret to CI

.github/workflows/production.yml
=> [POU-107] Production pipeline setup

src/@types/ProjectDetails.ts, src/components/atoms/ProjectDetailsVerificationList/ProjectDetailsVerificationList.spec.tsx, src/components/atoms/ProjectDetailsVerificationList/ProjectDetailsVerificationList.tsx, src/components/atoms/ProjectDetailsVerificationList/__snapshots__/ProjectDetailsVerificationList.spec.tsx.snap, src/components/molecules/ProjectDetailsVerification/ProjectDetailsVerification.tsx, src/components/molecules/ProjectDetailsVerification/__snapshots__/ProjectDetailsVerification.spec.tsx.snap, src/locales/en/projectDetails.json, src/styles/Button.ts, src/styles/Theme.ts, src/test/mock-data/project_detail.ts
[POU 61](https://cadtrust.atlassian.net/browse/POU-61)
Integrating expanding verification
- Creating the widget
- Adding test
=> [POU-61] Verification expanding

src/components/atoms/ProjectSearchBodyContent/ProjectSearchBodyContent.tsx, src/components/atoms/ProjectSearchHeadContent/ProjectSearchHeadContent.tsx, src/components/molecules/SearchHeader/SearchHeader.tsx
[POU 164](https://cadtrust.atlassian.net/browse/POU-164)
no empty search
- Add handling of go back for search
=> [POU-164] Not empty for search

src/@types/Unit.ts, src/@types/UnitSearchResult.ts, src/app/unit/issuance/__snapshots__/page.spec.tsx.snap, src/app/unit/issuance/page.tsx, src/components/atoms/ProjectDetailHeader/ProjectDetailHeader.tsx, src/components/atoms/UnitSearchBodyContent/UnitSearchBodyContent.tsx, src/components/atoms/UnitSearchHeadContent/UnitSearchHeadContent.tsx, src/components/molecules/OriginalIssuanceDetails/OriginalIssuanceDetails.spec.tsx, src/components/molecules/OriginalIssuanceDetails/OriginalIssuanceDetails.tsx, src/components/molecules/OriginalIssuanceDetails/__snapshots__/OriginalIssuanceDetails.spec.tsx.snap, src/components/organisms/Menu/Menu.tsx, src/components/organisms/Menu/__snapshots__/Menu.spec.tsx.snap, src/test/mock-data/unit_detail.ts, src/test/mock-data/units_data.ts
[POU 159](https://cadtrust.atlassian.net/browse/POU-159)
Adding details for the issuance page
- Add the OriginalIssuanceDetails
=> [POU-159] Finalizing issuance page

src/@types/Issuance.ts, src/@types/ProjectDetails.ts, src/app/__snapshots__/page.spec.tsx.snap, src/app/project/__snapshots__/page.spec.tsx.snap, src/app/project/page.tsx, src/components/atoms/NoDataScreen/NoDataScreen.spec.tsx, src/components/atoms/NoDataScreen/NoDataScreen.tsx, src/components/atoms/NoDataScreen/__snapshots__/NoDataScreen.spec.tsx.snap, src/components/molecules/IssuanceTable/IssuanceTable.tsx, src/components/molecules/IssuanceTable/__snapshots__/IssuanceTable.spec.tsx.snap, src/components/molecules/RetirementTable/RetirementTable.spec.tsx, src/components/molecules/RetirementTable/RetirementTable.tsx, src/components/molecules/RetirementTable/__snapshots__/RetirementTable.spec.tsx.snap, src/components/organisms/IssuancesRetirements/IssuancesRetirements.tsx, src/components/organisms/IssuancesRetirements/__snapshots__/IssuanceRetirements.spec.tsx.snap, src/components/organisms/ProjectDocuments/ProjectDocuments.spec.tsx, src/components/organisms/ProjectDocuments/ProjectDocuments.tsx, src/components/organisms/ProjectDocuments/__snapshots__/ProjectDocuments.spec.tsx.snap, src/locales/en/projectDetails.json, src/styles/SearchTable.ts, src/test/mock-data/project_detail.ts
[POU 166](https://cadtrust.atlassian.net/browse/POU-166)
Adding the project retirement table
- i18n
- RetirementTable
- ProjectDocuments
=> [POU-166] Retirements table

src/test/TestOvermindWrapper.tsx
=> [CHORE] Fixing on build

src/@types/ProjectDetails.ts, src/app/project/__snapshots__/page.spec.tsx.snap, src/app/project/page.tsx, src/components/atoms/BreadCrumbs/BreadCrumbs.tsx, src/components/atoms/EllipseIcon/EllipseIcon.spec.tsx, src/components/atoms/EllipseIcon/EllipseIcon.tsx, src/components/atoms/EllipseIcon/__snapshots__/EllipseIcon.spec.tsx.snap, src/components/atoms/ProjectBreadcrumb/ProjectBreadcrumb.tsx, src/components/atoms/ProjectBreadcrumb/__snapshots__/ProjectBreadcrumb.spec.tsx.snap, src/components/atoms/ProjectDetailsAnchor/ProjectDetailsAnchor.spec.tsx, src/components/atoms/ProjectDetailsAnchor/ProjectDetailsAnchor.tsx, src/components/atoms/ProjectDetailsAnchor/__snapshots__/ProjectDetailsAnchor.spec.tsx.snap, src/components/molecules/CardSection/CardSection.tsx
JIRA Ticket: POU-119
- Added anchor sections to Project Details page
- Updated breadcrumbs font size
- Added new ellipse icon component
- Updated CardSection to take design props
=> [POU-119] Anchor sections for project details top bar

src/@types/CSV.tsx, src/app/project/page.pdf.tsx, src/components/molecules/CSVDownload/CSVDownload.spec.tsx, src/components/molecules/CSVDownload/CSVDownload.tsx, src/components/organisms/ProjectCompareResultDrawer/ProjectCompareResultDrawer.spec.tsx, src/components/organisms/ProjectCompareResultDrawer/ProjectCompareResultDrawer.tsx, src/components/organisms/ProjectCompareResultDrawer/__snapshots__/ProjectCompareResultDrawer.spec.tsx.snap, src/test/mock-data/projects_data.ts, src/utils/CsvHelper.spec.ts, src/utils/CsvHelper.ts
JIRA Ticket: POU-235
- Update the filename conventions for Export feature
=> [POU-235] Filename update for exported files with timestamp

jest.config.js, sonar-project.properties, src/@types/State.ts, src/components/molecules/AuthenticationSection/AuthenticationSection.tsx, src/components/organisms/Menu/Menu.spec.tsx, src/overmind/authentication/actions.ts, src/overmind/authentication/index.ts, src/overmind/authentication/state.ts, src/overmind/index.ts
Need to be able to reference user information throughout the app
- Adding the authentication namespace in overmind
- Setting the namespace on login
=> [CHORE] Adding auth in overmind

src/components/atoms/UnitSearchHeadContent/UnitSearchHeadContent.tsx
JIRA Ticket: POU-215
- Fix for view project menu redirects to projects details with wrong id
=> [POU-215] View project from unit search result menu

src/@types/ProjectSearchResult.ts, src/components/atoms/ProjectSearchHeadContent/ProjectSearchHeadContent.tsx, src/components/atoms/WatchlistCheckbox/WatchlistCheckbox.spec.tsx, src/components/atoms/WatchlistCheckbox/WatchlistCheckbox.tsx, src/components/atoms/WatchlistCheckbox/__snapshots__/WatchlistCheckbox.spec.tsx.snap, src/components/molecules/AddWatchlistPopup/AddWatchlistPopup.spec.tsx, src/components/molecules/AddWatchlistPopup/AddWatchlistPopup.tsx, src/test/mock-data/projects_data.ts
Watchlist Checkbox should be pre-checked
- passing the watchlists of the selected project
=> [POU-187] Watchlist Checkbox should be pre-checked

src/app/watchlist/all/__snapshots__/page.spec.tsx.snap, src/app/watchlist/all/page.tsx, src/app/watchlist/view/__snapshots__/page.spec.tsx.snap, src/app/watchlist/view/page.tsx, src/components/atoms/WatchlistBreadcrumb/WatchlistBreadcrumb.spec.tsx, src/components/atoms/WatchlistBreadcrumb/WatchlistBreadcrumb.tsx, src/components/atoms/WatchlistBreadcrumb/__snapshots__/WatchlistBreadcrumb.spec.tsx.snap, src/locales/en/watchlist.json
[POU 187](https://cadtrust.atlassian.net/browse/POU-187)
Watchlist should have a breadcrumb
- Adding watchlist breadcrumb
=> [POU-187] Watchlsit breadcrumb

src/components/molecules/AuthenticationSection/AuthenticationSection.tsx, src/components/organisms/Menu/Menu.spec.tsx, src/components/organisms/Menu/__snapshots__/Menu.spec.tsx.snap
Description:
- Silently re-login user when page is reloaded
=> Auto login on page reload

src/components/molecules/AuthenticationSection/AuthenticationSection.tsx, src/components/organisms/AppHeader/AppHeader.tsx, src/components/organisms/AppHeader/Header.module.scss, src/components/organisms/AppHeader/__snapshots__/AppHeader.spec.tsx.snap, src/components/organisms/Menu/Menu.tsx, src/components/organisms/Menu/__snapshots__/Menu.spec.tsx.snap
=> [CHORE] Login button clickable

src/@types/ProjectDetails.ts, src/app/issuance/__snapshots__/page.spec.tsx.snap, src/app/issuance/page.tsx, src/app/project/page.tsx, src/app/unit/retirement/__snapshots__/page.spec.tsx.snap, src/app/unit/retirement/page.tsx, src/components/atoms/ProjectDetailHeader/ProjectDetailHeader.spec.tsx, src/components/atoms/ProjectDetailHeader/ProjectDetailHeader.tsx, src/components/atoms/ProjectDetailsVerificationList/__snapshots__/ProjectDetailsVerificationList.spec.tsx.snap, src/components/atoms/ProjectTypeBanner/ProjectTypeBanner.tsx, src/components/atoms/ProjectTypeBanner/__snapshots__/ProjectTypeBanner.spec.tsx.snap, src/components/molecules/IssuanceDetails/IssuanceDetails.tsx, src/components/molecules/IssuanceDetails/__snapshots__/IssuanceDetails.spec.tsx.snap, src/components/molecules/OriginalIssuanceDetails/OriginalIssuanceDetails.tsx, src/components/molecules/OriginalIssuanceDetails/__snapshots__/OriginalIssuanceDetails.spec.tsx.snap, src/components/molecules/ProjectDetailsVerification/ProjectDetailsVerification.tsx, src/components/molecules/ProjectDetailsVerification/__snapshots__/ProjectDetailsVerification.spec.tsx.snap, src/locales/en/projectDetails.json, src/locales/en/unitDetails.json
=> [POU-205] issuance details page fixes

package.json, pnpm-lock.yaml, src/@types/Issuance.ts, src/components/molecules/IssuanceDetails/IssuanceDetails.spec.tsx, src/components/molecules/IssuanceDetails/IssuanceDetails.tsx, src/components/molecules/IssuanceDetails/__snapshots__/IssuanceDetails.spec.tsx.snap
JIRA Ticket: POU-249
- Fix for Issuance details page error with empty tags
=> [POU-249] Issuance details tags fix

src/components/organisms/IssuancesRetirements/IssuancesRetirements.tsx, src/components/organisms/IssuancesRetirements/__snapshots__/IssuanceRetirements.spec.tsx.snap, src/overmind/analytics/effects.ts
JIRA Ticket: POU-253
- Sort issuances by vintage
=> [POU-253] Sort issuance by vintage ascending order in Project Details page

src/components/molecules/IssuanceDetails/IssuanceDetails.tsx, src/components/molecules/IssuanceDetails/__snapshots__/IssuanceDetails.spec.tsx.snap, src/components/molecules/OriginalIssuanceDetails/OriginalIssuanceDetails.spec.tsx, src/components/molecules/OriginalIssuanceDetails/OriginalIssuanceDetails.tsx, src/components/molecules/OriginalIssuanceDetails/__snapshots__/OriginalIssuanceDetails.spec.tsx.snap
JIRA Ticket: POU-254
- Fix for Project Issued To data
=> [POU-254] Project Issued To should show Project name

src/components/molecules/ProjectDetailsInfo/ProjectDetailsInfo.spec.tsx, src/components/molecules/ProjectDetailsInfo/ProjectDetailsInfo.tsx, src/components/molecules/ProjectDetailsInfo/__snapshots__/ProjectDetailsInfo.spec.tsx.snap, src/locales/en/projectDetails.json
JIRA Ticket: POU-262
- Added Validation details in project page
=> [POU-262] Added Validation details in Project page

src/components/molecules/ProjectDetailsInfo/__snapshots__/ProjectDetailsInfo.spec.tsx.snap, src/overmind/creditsHistory/effects.ts
JIRA Ticket: POU-264
- Fixed date comparison to format data correctly for graph
=> [POU-264] Wrong graph visualization data

src/components/organisms/AppHeader/AppHeader.tsx, src/components/organisms/AppHeader/__snapshots__/AppHeader.spec.tsx.snap, src/styles/Button.ts
JIRA Ticket: POU-268
- Fixed hover color of **Find out more** button
- Fixed redirect url
=> [POU-268] button hover color fix

src/components/molecules/AuthenticationSection/AuthenticationSection.tsx, src/components/organisms/CreditsHistorySection/__snapshots__/CreditsHistorySection.spec.tsx.snap, src/components/organisms/Menu/__snapshots__/Menu.spec.tsx.snap
JIRA Ticket: POU-265
Update Login Button text to use Menu Locale file's String
=> :recycle: refactor: Changed text on login button to use the locale file

src/components/molecules/CreditsHistoryChart/CreditsHistoryLineChart.tsx
JIRA Ticket: POU-281
Update X-Axis to display by month
=> :lipstick: style: Change X-Axis to use months

src/components/organisms/CreditsHistorySection/IssuedRetiredChartBody.tsx, src/components/organisms/CreditsHistorySection/__snapshots__/CreditsHistorySection.spec.tsx.snap, src/components/organisms/CreditsHistorySection/__snapshots__/IssuedRetiredChartBody.spec.tsx.snap
=> :bug: fix: disable retired graph line

src/components/organisms/CreditsHistorySection/CreditsHistorySection.tsx, src/components/organisms/CreditsHistorySection/IssuedRetiredChartBody.tsx, src/components/organisms/CreditsHistorySection/__snapshots__/CreditsHistorySection.spec.tsx.snap, src/components/organisms/CreditsHistorySection/__snapshots__/IssuedRetiredChartBody.spec.tsx.snap
=> :bug: fix: Disable Chart Line

src/components/atoms/GoogleMapWidget/GoogleMapWidget.spec.tsx, src/components/atoms/GoogleMapWidget/GoogleMapWidget.tsx
JIRA Ticket: POU-289
Add retry when fetching Google Map Coordinates after reloading. Affects those that need text searching.
=> :bug: fix: Add retry when loading coordinates

src/components/molecules/CalendarWrapper/CalendarWrapper.spec.tsx, src/components/molecules/CalendarWrapper/__snapshots__/CalendarWrapper.spec.tsx.snap, src/components/organisms/WatchlistProjects/WatchlistProjects.tsx
JIRA Ticket: POU-333
Description (Optional): Original feature was not fully implemented. Removing to remove confusion among users.
=> :bug: fix: Remove Export Watchlist button
